version: '3.8'
services:

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    depends_on:
      - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=doumbiaalmoustapha@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
    ports:
      - '8000:80'
volumes:
  db:
    driver: local